# Service status
SERVICE_STATUS_ONLINE = "online"
SERVICE_STATUS_OFFLINE = "offline"

# ENV variables
ENV_DOT_FILE = "ENV"
ENV_CONFIG_PREFIX = "SCIUROMORPHA_"
ENV_CONFIG_MODE = ENV_CONFIG_PREFIX + "MODE"
ENV_CONFIG_FILE = ENV_CONFIG_PREFIX + "CONFIG"

# Enviroment modes.
ENV_MODE_DEVELOPMENT = "development"
ENV_MODE_PRODUCTION = "production"
ENV_MODE_TEST = "test"

# Config Section
CONFIG_SECTION_STORAGE = "storage"
CONFIG_SECTION_FS = "fs"
CONFIG_SECTION_CACHE = "cache"
CONFIG_SECTION_DOCKER = "docker"
